name: Backend CI/CD

on: [push]

jobs:
    build:
  
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd ./back
      - run: npm install
      - run: npm run build
      - run: npm start
        env:
          CI: true
            


